### ISSUE TITLE
Exception thrown sometimes on client and server (after longish period of viewing the radiator)

### ISSUE THREAD

**Issue by heikkipora** [heikkipora/gitlab-radiator#23]
<img width="963" alt="screen shot 2018-02-01 at 15 06 39" src="https://user-images.githubusercontent.com/259924/35733794-6a801a32-0827-11e8-8d20-8a2c80bff57e.png">

**Comment by heikkipora** [comment]
Might be related (on the server side)

```
2018-02-01T20:39:24.900077+00:00 app[web.1]: TypeError: Cannot read property 'title' of null
2018-02-01T20:39:24.900089+00:00 app[web.1]: at _callee4$ (/app/node_modules/gitlab-radiator/src/gitlab/pipelines.js:179:31)
2018-02-01T20:39:24.900093+00:00 app[web.1]: at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
2018-02-01T20:39:24.900095+00:00 app[web.1]: at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)
2018-02-01T20:39:24.900097+00:00 app[web.1]: at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:114:21)
2018-02-01T20:39:24.900099+00:00 app[web.1]: at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
2018-02-01T20:39:24.900100+00:00 app[web.1]: at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
2018-02-01T20:39:24.900103+00:00 app[web.1]: at <anonymous>
```

**Comment by heikkipora** [comment]
Exact conditions for the cause are unknown (other then the fact that commit information is not available for a job)

Fixed by https://github.com/heikkipora/gitlab-radiator/commit/0c85f41979410a2607a339ad0355998ed2fbc974
